config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  root "store#index", as: "store_index"
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, :price, presence: true
  validates :title, uniqueness: true, length: { minimum: 10 }
  validates :price, numericality: { greater_than_or_equal_to: 1 }

  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line Items present")
      throw :abort
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :course
  belongs_to :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy!

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy!

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart

  before_action :set_cart, only: %i[ create ]
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    course = Course.find(params[:course_id])
    @line_item = @cart.line_items.build(course: course)

    respond_to do |format|
      if @line_item.save
        session[:counter] = nil
        format.html { redirect_to cart_url(@line_item.cart), notice: "Line item was successfully created." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy!

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:course_id, :cart_id)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  before_action :visit_counter
  def index
    @courses = Course.order(:title)
  end

  private

  def visit_counter
    return session[:counter] = 1 if session[:counter].nil?

    session[:counter] = session[:counter] + 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
  <h2 class="font-bold text-lg mb-3">BeliKursus Cart</h2>
  <ul>
    <% cart.line_items.each do |item| %>
      <li><%= item.course.title %></li>  
      <li><%= item.course.description %></li>  
      <br>
      <br>
    <% end %>
  </ul>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, class: "contents") do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing cart</h1>

  <%= render "form", cart: @cart %>

  <%= link_to "Show this cart", @cart, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to carts", carts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/carts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Carts" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Carts</h1>
    <%= link_to "New cart", new_cart_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="carts" class="min-w-full">
    <% @carts.each do |cart| %>
      <%= render cart %>
      <p>
        <%= link_to "Show this cart", cart, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/carts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New cart</h1>

  <%= render "form", cart: @cart %>

  <%= link_to "Back to carts", carts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/carts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @cart %>

    <%= link_to "Edit this cart", edit_cart_path(@cart), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to carts", carts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this cart", @cart, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= course.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= course.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Image url:</strong>
    <%= course.image_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= course.price %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course, class: "contents") do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing course</h1>

  <%= render "form", course: @course %>

  <%= link_to "Show this course", @course, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to courses", courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/courses/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center pb-8">
    <h1 class="mx-auto text-lg font-bold">Courses</h1>
  </div>

  <table id="courses" class="mx-auto">
    <tfoot>
      <tr>
        <td colspan="3">
          <div class="mt-8">
            <%= link_to 'New course',
              new_course_path,
              class: "inline rounded-lg py-3 px-5 bg-green-600 text-white block font-medium" %>
          </div>
        </td>
      </tr>
    <tfoot>
    
    <tbody>
      <% @courses.each do |course| %> 
        <tr class="<%= cycle('bg-red-100', 'bg-white') %>">
          <td class="px-2 py-3">
            <%= image_tag(course.image_url, class: 'w-40') %>
          </td>
          <td>
            <h1 class="text-xl font-bold mb-3"><%= course.title %></h1>
            <p>
              <%= truncate(strip_tags(course.description), length: 80) %>
            </p>
          </td>
          <td class="px-3">
            <ul>
              <li>
                <%= link_to 'Show', course, class: 'hover:underline' %>
              </li>
              <li>
                <%= link_to 'Edit', edit_course_path(course), class: 'hover:underline' %>
              </li>
              <li>
                <%= link_to 'Destroy', course, class: 'hover:underline', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
              </li>
            </ul>
          </td>
        </tr> 
      <% end %>
    </tbody>
  </table>

app/views/courses/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New course</h1>

  <%= render "form", course: @course %>

  <%= link_to "Back to courses", courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/courses/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @course %>

    <%= link_to "Edit this course", edit_course_path(@course), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to courses", courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this course", @course, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Belikursus" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-200 flex">
    <nav class="bg-gray-800 text-white w-64 min-h-screen flex flex-col">
      <div class="p-4">
        <%= image_tag "https://via.placeholder.com/150x50?text=BeliKursus", alt: "logo", class: "w-full" %>
      </div>

      <ul class="flex-grow">
        <li><%= link_to "Home", "#", class: "block py-2 px-4 hover:bg-gray-700" %></li>
        <li><%= link_to "Courses", "#", class: "block py-2 px-4 hover:bg-gray-700" %></li>
        <li><%= link_to "About Us", "#", class: "block py-2 px-4 hover:bg-gray-700" %></li>
        <li><%= link_to "Contact", "#", class: "block py-2 px-4 hover:bg-gray-700" %></li>
      </ul>
    </nav>

    <main class="flex-grow p-8">
      <%= yield %>
    </main>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, class: "contents") do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :course_id %>
    <%= form.text_field :course_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<div id="<%= dom_id line_item %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Course:</strong>
    <%= line_item.course_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Cart:</strong>
    <%= line_item.cart_id %>
  </p>

</div>

app/views/line_items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing line item</h1>

  <%= render "form", line_item: @line_item %>

  <%= link_to "Show this line item", @line_item, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to line items", line_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/line_items/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Line items" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Line items</h1>
    <%= link_to "New line item", new_line_item_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="line_items" class="min-w-full">
    <% @line_items.each do |line_item| %>
      <%= render line_item %>
      <p>
        <%= link_to "Show this line item", line_item, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/line_items/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New line item</h1>

  <%= render "form", line_item: @line_item %>

  <%= link_to "Back to line items", line_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/line_items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @line_item %>

    <%= link_to "Edit this line item", edit_line_item_path(@line_item), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to line items", line_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this line item", @line_item, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/store/index.html.erb
<div class="container mx-auto px-4 py-8">
  <% if session[:counter] > 5 %>
    <p><%= "#{session[:counter]} #{"visit".pluralize(session[:counter])}" %></p>
  <% end %>

  <h1 class="text-3xl font-bold mb-6 text-center">Courses Catalog</h1>

  <div class="grid grid-cols-4 gap-7">
    <% cache @courses do %>
      <% @courses.each do |course| %>
        <% cache course do %>
          <div class="bg-white rounded-lg shadow-md overflow-hidden flex flex-col">
            <div class="aspect-w-16 aspect-h-8">
              <%= image_tag course.image_url %>
            </div>
            <div class="p-4 flex flex-col flex-grow">
              <h2 class="text-lg font-semibold mb-2"><%= course.title %></h2>
              <p class="text-sm text-gray-600 mb-4 flex-grow"><%= truncate(strip_tags(course.description)) %></p>
              <div class="mt-3">
                <%= number_to_currency(course.price, unit: "IDR ", separator: ",", delimiter: ".") %>
              </div>
              <div class="flex justify-between">
                <%= link_to "Show", "#", class: "bg-gray-500 text-white text-center px-4 py-2 rounded hover:bg-gray-600 transition duration-300 flex-grow mr-2" %>
                <%= button_to "Add to Cart",
                  line_items_path(course_id: course.id),
                  class: "bg-blue-500 text-white text-center px-4 py-2 rounded hover:bg-blue-600 transition duration-300 flex-grow ml-2"  %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>